### ISSUE TITLE
OSX El Cap install issue

### ISSUE THREAD

**Issue by chrisrikli** [Randonee/easybuild#1]
El Cap won't allow the creation of a file in /usr/bin, even by root or sudoer.

More info here: http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really

I'll split off a working branch from master and createa fix.  

Then I will create a pull request if given access to this repo or will alternatively post a patch.

**Comment by chrisrikli** [comment]
Fix patch attached.  Implements a crude check for OSX.  Please note, this does not check OSX _version_...could not find a haxe function to do this.  

[0001-updated-the-code-to-check-for-OSX.patch.txt](https://github.com/Randonee/easybuild/files/373905/0001-updated-the-code-to-check-for-OSX.patch.txt)

**Comment by Randonee** [comment]
Perfect thanks. Patch applied.
